### ISSUE TITLE
Busan meeting notes MC definition

### ISSUE THREAD

**Issue by eguil** [CLIVAR-PRP/ENSO_metrics#12]
Notes from ENSO RF exchanges to define metrics collections

**Comment by eguil** [comment]
**Busan Oct 2017 Meeting TODO list**

- ENSO performance in historical [Andrew, Antonietta, Mike, Matt, Scott,…]
  - Mean state incl. SC, ENSO characteristic space/time, diversity, decadal
  - Use ensemble or Picontrol to evaluate uncertainty
- ENSO teleconnections in historical [Scott, Wenju, Sarah, Shayne, Lisa…)
  - Metrics a la Scott (25 regions,…), RMS,…
- ENSO processes (right for right reasons) [Soon-Il, Masahiro, Eric,…]

**What to provide (10 max):**

- Documentation: whys and hows of the metric and the collection
- Math definition of the metric
- Frequency (DA, MO,…)
- Observations (as many as possible), including which period to use
- Reference to show the robustness of metric
- Minimum number of realisations  (for metric to make sense)
- Minimum lenght of simulation needed (for metric to make sense)
- « Dive down » diag (map of RMS,…)
- Normalisation wrt sharing single color bar in a MME env.
- Monthly telcos,

 First draft Dec 15th, review by experts, second draft feb 15th

**Comment by eguil** [comment]
**Telecon 17 Nov 2017 (Andrew, Antonietta, Matt, Eric):**
- Andrew presented first list of "Basic ENSO-related metrics" 
[ENSO_MC1_Nov17_atw.pptx](https://github.com/eguil/ENSO_metrics/files/1482916/ENSO_MC1_Nov17_atw.pptx)
- **TODO [AW]**: provide above list of items for
 - Mean state examples (SST at Eq and precip 15S-25N in East Pac)
 - Mean Seasonality of SST 
 - El Nino and La Nina composite SST RMSE
 - ENSO SST seasonality (look also at Bellenger et al. metric)
 - other ?

**Comment by lee1043** [comment]
@eguil  https://github.com/eguil/ENSO_metrics/wiki This might be good starting place for the documentation.
