### ISSUE TITLE
Package dict{} output format

### ISSUE THREAD

**Issue by eguil** [CLIVAR-PRP/ENSO_metrics#17]
2 levels of doc:
**Level A: provided via output of package** (short science provenance) in dict{}
1. dict for doc:
 - Metric collection 
   - name and description
   - parent MC further info URL
 - per metric (no info on model and actual values)
   - metric long name and description
   - method to compute the metric
   - units
   - time frequency
   - reference observations
   - time period for reference observations
   - child metric further info URL

2. dict for actual calculation:
 - diagnostic per reference observation 
 - diagnostic per model
   - time period for model
 - metric values

**_[ more thinking needed for organisation ]_**

**Level B: more comprehensive via a URL** in short science provenance
  - parent MC URL: ```https://github.com/eguil/ENSO_metrics/wiki/<MetricCollection>```
  - child metric URL: ```https://github.com/eguil/ENSO_metrics/wiki/<Metric>```

**Comment by lee1043** [comment]
- Completed at: https://github.com/CLIVAR-PRP/ENSO_metrics/wiki
- Closing the issue for house cleaning
