### ISSUE TITLE
API ENSO metrics lib

### ISSUE THREAD

**Issue by eguil** [CLIVAR-PRP/ENSO_metrics#5]
API output:
- name
- metric(s) value, diff with obs
- unit(s)
- reference obs
- method
- reference
- range of graphic display ("red-blue" for "worse-better" in portrait plots)
- number of years/month in calculation

**Comment by gleckler1** [comment]
@eguil @yyplanton @lee1043  All of these (expect plotting info) will be documented in the JSON output of results as part of the provenance.

**Comment by eguil** [comment]
Organised output (dict) in to 2 parts (metadata, data)
